export interface PortfolioItem {
  id: string
  name: string
  type: "Job Experience" | "Investment" | "Incubation" | "Portfolio" | "Company"
  theme: "Invest" | "Timeline" | "Portfolio" | "Technology" | "Hospitality" | "Education" | "Healthcare" | "Innovation"
  associations: string[]
  description: string
  website?: string
  percentage?: number
  color?: string
}

export const portfolioData: PortfolioItem[] = [
  {
    id: "spacex",
    name: "SpaceX",
    type: "Investment",
    theme: "Technology",
    associations: ["Sandeep", "Dheeraj"],
    description: "Private space exploration and satellite internet company revolutionizing space travel.",
    website: "https://spacex.com",
    color: "bg-pink-200",
  },
  {
    id: "groq",
    name: "Groq",
    type: "Investment",
    theme: "Technology",
    associations: ["Dheeraj", "Sandeep"],
    description: "High-performance AI inference company specializing in Language Processing Units (LPUs).",
    website: "https://groq.com",
    color: "bg-yellow-200",
  },
  {
    id: "groq2",
    name: "Groq2",
    type: "Investment",
    theme: "Technology",
    associations: ["Sandeep", "Dheeraj"],
    description: "Next generation AI processing technology and infrastructure platform.",
    color: "bg-blue-200",
  },
  {
    id: "perplexity",
    name: "Perplexity",
    type: "Investment",
    theme: "Technology",
    associations: ["Sandeep", "Praveen"],
    description: "AI-powered search engine providing accurate, real-time information with citations.",
    website: "https://perplexity.ai",
    color: "bg-blue-200",
  },
  {
    id: "xai",
    name: "xAi",
    type: "Investment",
    theme: "Technology",
    associations: ["Dheeraj", "Sandeep"],
    description: "AI company focused on understanding the universe through advanced AI systems.",
    color: "bg-green-200",
  },
  {
    id: "elite-hyd",
    name: "Elite Hyd",
    type: "Investment",
    theme: "Hospitality",
    associations: ["Sandeep", "Praveen"],
    description: "Premium hospitality and real estate development company in Hyderabad.",
    percentage: 55,
    color: "bg-yellow-200",
  },
  {
    id: "zostel-hyderabad",
    name: "Zostel Hyderabad",
    type: "Investment",
    theme: "Hospitality",
    associations: ["Dheeraj", "Sandeep", "Srikanth", "Kader"],
    description: "Premium backpacker hostel providing affordable accommodation and community experiences.",
    website: "https://zostel.com",
    percentage: 90,
    color: "bg-yellow-200",
  },
  {
    id: "zostel-chennai",
    name: "Zostel Chennai",
    type: "Investment",
    theme: "Hospitality",
    associations: ["Sandeep", "Praveen"],
    description: "Chennai branch of the popular backpacker hostel chain.",
    percentage: 20,
    color: "bg-yellow-200",
  },
  {
    id: "young-monk-dharamshala",
    name: "Young Monk Dharamshala",
    type: "Investment",
    theme: "Hospitality",
    associations: ["Praveen", "Sandeep"],
    description: "Boutique accommodation and wellness retreat in the spiritual heart of Dharamshala.",
    percentage: 40,
    color: "bg-yellow-200",
  },
  {
    id: "manabadi",
    name: "Manabadi",
    type: "Incubation",
    theme: "Education",
    associations: ["Praveen", "Sandeep"],
    description: "Educational technology platform providing online learning resources and exam preparation.",
    website: "https://manabadi.com",
    color: "bg-yellow-200",
  },
  {
    id: "sampada",
    name: "Sampada",
    type: "Incubation",
    theme: "Education",
    associations: ["Sandeep", "Dheeraj"],
    description: "Digital learning platform focused on skill development and professional training.",
    color: "bg-yellow-200",
  },
  {
    id: "internships",
    name: "Internships",
    type: "Portfolio",
    theme: "Education",
    associations: ["Sandeep", "Praveen", "Dheeraj"],
    description: "Comprehensive internship program connecting students with industry opportunities.",
    color: "bg-yellow-200",
  },
  {
    id: "incubation",
    name: "Incubation",
    type: "Portfolio",
    theme: "Innovation",
    associations: ["Sandeep", "Dheeraj"],
    description: "Startup incubation program supporting early-stage technology companies.",
    color: "bg-yellow-200",
  },
  {
    id: "roche",
    name: "ROche",
    type: "Job Experience",
    theme: "Healthcare",
    associations: ["Sandeep"],
    description: "Global healthcare company focused on pharmaceuticals and diagnostics.",
    website: "https://roche.com",
    color: "bg-yellow-200",
  },
  {
    id: "tide",
    name: "TIde",
    type: "Job Experience",
    theme: "Technology",
    associations: ["Praveen"],
    description: "Digital banking platform for small and medium enterprises.",
    website: "https://tide.co",
    color: "bg-yellow-200",
  },
  {
    id: "google",
    name: "Google",
    type: "Job Experience",
    theme: "Technology",
    associations: ["Dheeraj", "Sandeep"],
    description: "Global technology company specializing in internet-related services and products.",
    website: "https://google.com",
    color: "bg-yellow-200",
  },
  {
    id: "meta",
    name: "Meta",
    type: "Job Experience",
    theme: "Technology",
    associations: ["Sandeep", "Praveen"],
    description: "Social technology company building the next evolution of social connection.",
    website: "https://meta.com",
    color: "bg-yellow-200",
  },
  {
    id: "block",
    name: "Block",
    type: "Job Experience",
    theme: "Technology",
    associations: ["Dheeraj"],
    description: "Financial services and digital payments company formerly known as Square.",
    website: "https://block.xyz",
    color: "bg-yellow-200",
  },
  {
    id: "reddit",
    name: "Reddit",
    type: "Job Experience",
    theme: "Technology",
    associations: ["Praveen", "Dheeraj"],
    description: "Social news aggregation and discussion platform.",
    website: "https://reddit.com",
    color: "bg-yellow-200",
  },
  {
    id: "atoks",
    name: "Atoks",
    type: "Portfolio",
    theme: "Technology",
    associations: ["Sandeep", "Dheeraj"],
    description: "Innovative technology solutions and digital transformation services.",
    color: "bg-yellow-200",
  },
  {
    id: "srd-innovation-fund",
    name: "SRD Innovation Fund",
    type: "Company",
    theme: "Innovation",
    associations: ["SRD"],
    description: "Venture capital fund focused on early-stage technology and innovation investments.",
    color: "bg-yellow-200",
  },
  {
    id: "sanskrut-corp",
    name: "Sanskrut Corp",
    type: "Company",
    theme: "Portfolio",
    associations: ["Sanskrut Corp"],
    description: "Corporate holding company with diversified business interests and investments.",
    color: "bg-yellow-200",
  },
  {
    id: "sanskrut-enterprises",
    name: "Sanskrut Enterprises",
    type: "Company",
    theme: "Portfolio",
    associations: ["Sanskrut Ent"],
    description: "Business enterprise focused on strategic investments and operational excellence.",
    color: "bg-yellow-200",
  },
]

// Entity configurations for personalized sites
export const entityConfigs = {
  sandeep: {
    name: "Sandeep",
    title: "Investor & Technology Leader",
    description: "Building the future through strategic investments and technology innovation",
    theme: "Investor, Job, Timeline",
  },
  praveen: {
    name: "Praveen",
    title: "Portfolio Manager & Strategist",
    description: "Driving growth through strategic portfolio management and business development",
    theme: "Portfolio",
  },
  dheeraj: {
    name: "Dheeraj",
    title: "Technology Executive & Investor",
    description: "Scaling technology companies and driving innovation in AI and fintech",
    theme: "Technology",
  },
  srd: {
    name: "SRD",
    title: "Innovation Fund",
    description: "Investing in breakthrough technologies and disruptive innovations",
    theme: "Invest",
  },
  "sanskrut-corp": {
    name: "Sanskrut Corp",
    title: "Corporate Holdings",
    description: "Diversified corporate investments and strategic business development",
    theme: "Portfolio",
  },
  "sanskrut-ent": {
    name: "Sanskrut Enterprises",
    title: "Business Enterprises",
    description: "Strategic business operations and investment management",
    theme: "Portfolio",
  },
}
